<?php
/**
 * Plugin Name:       Lupyx Dynamic Fields for Elementor
 * Plugin URI:        https://github.com/nuvyrex/lupyx-dynamic-fields-for-elementor
 * Description:       Render ACF Pro field data (Repeater and more) inside Elementor Pro's Loop Grid widget — no code required. Built on a filter-driven Field Type Provider architecture for easy extension.
 * Version:           0.0.2
 * Requires at least: 6.5
 * Requires PHP:      7.4
 * Requires Plugins:  elementor
 * Author:            devnexus
 * Author URI:        https://github.com/nuvyrex
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       lupyx-dynamic-fields-for-elementor
 *
 * @package LupyxSyncDynamicFields
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ---------------------------------------------------------------------------
// Constants — all prefixed LPDFE_ to avoid collisions.
// ---------------------------------------------------------------------------

/** @var string Plugin version. */
define( 'LPDFE_VERSION', '0.0.2' );

/** @var string Absolute path to the main plugin file. */
define( 'LPDFE_FILE', __FILE__ );

/** @var string Absolute path to the plugin root directory, with trailing slash. */
define( 'LPDFE_DIR', plugin_dir_path( __FILE__ ) );

/** @var string Full URL to the plugin root directory, with trailing slash. */
define( 'LPDFE_URL', plugin_dir_url( __FILE__ ) );

/** @var string Minimum required Elementor version. */
define( 'LPDFE_MIN_ELEMENTOR', '3.21.0' );

/** @var string Minimum required Elementor Pro version. */
define( 'LPDFE_MIN_ELEMENTOR_PRO', '3.21.0' );

/** @var string Minimum required ACF Pro version. */
define( 'LPDFE_MIN_ACF', '6.0.0' );

// ---------------------------------------------------------------------------
// Autoloader — Composer PSR-4; generated by `composer dump-autoload`.
// ---------------------------------------------------------------------------

if ( file_exists( LPDFE_DIR . 'vendor/autoload.php' ) ) {
	require_once LPDFE_DIR . 'vendor/autoload.php';
} else {
	// Autoloader missing — show admin notice and bail gracefully.
	add_action(
		'admin_notices',
		static function () {
			printf(
				'<div class="notice notice-error"><p>%s</p></div>',
				esc_html__(
					'Lupyx Dynamic Fields for Elementor: Composer autoloader not found. Run "composer install" inside the plugin directory.',
					'lupyx-dynamic-fields-for-elementor'
				)
			);
		}
	);
	return;
}

\LupyxSyncDynamicFields\Plugin::instance();
